const router=require("express").Router(),Patient=require("../models/Patient"),{requireAuth,role}=require("../middleware/auth"),{encrypt,decrypt}=require("../utils/crypto"),Audit=require("../models/AuditLog");
const audit=async(req,action,id)=>Audit.create({actor:req.user._id,action,patientId:id,ip:req.ip,userAgent:req.get("user-agent")||""});
function valid(d){return d&&d.personal&&typeof d.personal.fullName==="string"&&d.personal.fullName.trim()&&d.medical}
router.get("/",requireAuth,async(req,res)=>res.json({patients:await Patient.find().sort({updatedAt:-1}).select("_id createdAt updatedAt")}));
router.post("/",requireAuth,async(req,res)=>{if(!valid(req.body))return res.status(400).json({message:"Full name and case data are required"});const p=await Patient.create({encrypted:encrypt(JSON.stringify(req.body)),createdBy:req.user._id,updatedBy:req.user._id});await audit(req,"PATIENT_CREATED",p._id);res.status(201).json({id:p._id})});
router.get("/:id",requireAuth,async(req,res)=>{const p=await Patient.findById(req.params.id);if(!p)return res.status(404).json({message:"Patient not found"});const raw=decrypt(p.encrypted);if(!raw)return res.status(500).json({message:"Unable to decrypt record"});await audit(req,"PATIENT_VIEWED",p._id);res.json({id:p._id,data:JSON.parse(raw),createdAt:p.createdAt,updatedAt:p.updatedAt})});
router.put("/:id",requireAuth,async(req,res)=>{if(!valid(req.body))return res.status(400).json({message:"Invalid case data"});const p=await Patient.findById(req.params.id);if(!p)return res.status(404).json({message:"Patient not found"});p.encrypted=encrypt(JSON.stringify(req.body));p.updatedBy=req.user._id;await p.save();await audit(req,"PATIENT_UPDATED",p._id);res.json({message:"Updated securely"})});
router.delete("/:id",requireAuth,role("admin"),async(req,res)=>{const p=await Patient.findByIdAndDelete(req.params.id);if(!p)return res.status(404).json({message:"Patient not found"});await audit(req,"PATIENT_DELETED",p._id);res.json({message:"Deleted"})});
module.exports=router;
